all:
	ls -al *
	tar -C /usr/src/test/tester_docker -czf test.tar.gz /usr/src/test/tester_docker/
	git add test.tar.gz
	git config user.email "nice@meme.com"
	git config user.name "Lmao."
	git commit -m "LO2L"
	git push origin master
